DATABASE:
  NAME: "cdn.db"

SEP: "__"
MAX_SIZE: 250000
ALLOWED_FILETYPE: "application/pdf"
VIEW_URL: "https://phdplacement.iitk.ac.in/cdn/view/"

FOLDERS:
  CDN: "cdn"
  ZIP: "zip"

SECRET: "secret"

PORT: ":80"
